# Site settings
name: SpongeBob
email: 787121369@qq.com
author: 靓仔小馒头
url: https://oldrive.github.io/
resume_site: https://oldrive.github.io/Resume.io/
github: https://github.com/oldrive/
baseurl: ""
description: 不管你是否愿意相信，在美丽的比基尼海滩，每个岩洞下，都藏着一个奇迹！
meta_description: 胡晓平;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Life is cherished by everyone,but time by few
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: oldrive

# Build settings
markdown: kramdown

baidu_analysis: a1a0ef55055b063e13450fcfd6336770


revolvermaps: 0qvdxjsw632
